SitePro Fix
mahtab2003/Xera pull request #53
Opened 2022-09-26 20:31 UTC by gilect-com

Fixed SitePro from creating a website in the wrong directory, when using a domain other than the Account Domain. Previously it was created at /htdocs/domain
When it should be at /domain/htdocs instead

2022-09-26 20:57 UTC, greenreader9 commented
DO NOT DO THIS!!!

This is will break the base domain of the account (The domain that the account was created with). 

The solution is to programmatically determine what to do, there is not a "Always This" or "Always That" solution.

2022-09-26 20:59 UTC, greenreader9 requested changes
This will break original domain on the account

2022-09-27 03:25 UTC, gilect-com commented
Why exactly is this breaking the original domain?

All this is doing is preventing files from being created in
/htdocs/_domain_
(a directory which does not exist)
Instead they should be created in
/_domain_/htdocs/

Using the website builder on the original Account Domain still works fine, it creates the files in
/htdocs/

2022-09-27 16:29 UTC, 4yx commented
> This will break original domain on the account

Could you explain how it would break it?

2022-09-27 20:45 UTC, greenreader9 commented
Ah, I think I misread the code, stupid GitHub app did not show me what I needed to see. 

My apologies, this should actually work. 

@mahtab2003 Can you merge this?
Thanks

2022-09-27 22:07 UTC, 4yx commented
It looks good from my end as well, I'll attempt to test it out.

2022-09-27 23:14 UTC, gilect-com commented
It should work, all it does it change the directory where SitePro files are created. I applied the change myself and it fixes the SitePro bug that previously occured.

2022-09-28 18:03 UTC, 4yx commented
This should be safe to merge, yes. @mahtab2003 could you reopen and merge this?

2022-09-29 12:51 UTC, merged